Fix unhandled exceptions causing game-breaking issues
kd8lvt/RimWorld-Math pull request #12
Opened 2024-11-16 00:55 UTC by Jacbo1

The bill dialogs in my game were flickering, and interacting with certain UI components in certain bills would permanently break the entire bill dialog and its sub-dialogs rendering them unusable because there was no error handling. The errors in the log all pointed to this addon. One repeating error reported a null reference while another reported an unmatching amount of `BeginScrollView` and `EndScrollView` calls. The changes in this PR are almost entirely whitespace despite what GitHub actually shows (GitHub Desktop is actually able to properly determine the whitespace-only changes). All that has been added is many try-finally wrappings on begin-end patterns and a try-catch in the foreach loop inside `RenderLinkSettings`. `node.Render(lt, 0);` was throwing exceptions as sometimes `node` was null and then this would fall out of the `RenderLinkSettings` method entirely causing the `Widgets.BeginScrollView(render_area, ref linkSettingsScrollPos, scroll_area);` to never reach its closing `Widgets.EndScrollView();` which caused this game-breaking behavior. This try-finally pattern was applied to all other ImGui begin-end patterns as a precaution to ensure that anywhere there is an exception, anything that was started with a `begin` will be ended.

2024-11-17 20:58 UTC, kd8lvt requested changes
Other than a lack of error reporting, looks good to me. Whether you implement error reporting in the way I suggested or otherwise, I'll pull and do a release when you've done so :)

Thanks for this! It's something I've been meaning to do, but Life™ has been a nuisance recently.

2024-11-17 20:58 UTC, kd8lvt commented on Source/Dialogs/Dialog_MathBillConfig.cs
> +			finally
I'd like to have some error logging, mainly to prevent confusion when otherwise valid bills fail to resolve.

As it stands this just completely ignores errors, rather than solving them or even notifying the user that their bill may fail to resolve.

Something along these lines would be great--
```cs
//Math.cs
public static List<Exception> loggedExceptions = new List<Exception>();
//...
public static void tryLogException(Exception e) {
  if (loggedExceptions.Contains(e)) return;
  Log.Error("Encountered an error while resolving a bill - logging it once and trying to recover smoothly.")
  Log.Error(e)
  loggedExceptions.Add(e);
}
//...
```
```cs
try {
  //...
} catch (Exception e) {
  Math.tryLogException(e)
} finally {
  //...
}
```

2024-11-17 21:55 UTC, Jacbo1 commented on Source/Dialogs/Dialog_MathBillConfig.cs
> +			finally
I'm not totally sure if there's confusion here or not. I didn't add any catches so the errors will still be thrown and logged.

2024-11-17 22:03 UTC, Jacbo1 commented on Source/Dialogs/Dialog_MathBillConfig.cs
> +			finally
Additionally, since Exceptions are classes and don't seem to override the `.Equals()` method, I'm fairly certain you wouldn't be able to do a one-time log like this.

2024-11-17 22:19 UTC, kd8lvt commented on Source/Dialogs/Dialog_MathBillConfig.cs
> +			finally
I know the issues are coming from Math, it's been on my todo list to fix this for a while, just haven't been able to touch RimWorld for quite a while because of things going on IRL.  
> I didn't add any catches so the errors will still be thrown [...]  

Ah, I see. That'd log (potentially multiple) exceptions every frame, very quickly filling out the log length limit, which is... not ideal. Doing a one-time log would be much prefered.  

> Since Exceptions are classes that don't seem to override `.Equals()` [...]  

You should be able to, though you might have to `toString` it first. There's a way I've done it in the past, I just can't remember right now for the life of me. Give it a try, and if you can't get it working it's not a big deal I'll make-do.

2024-11-18 02:48 UTC, kd8lvt approved these changes

2024-11-18 02:48 UTC, merged

2024-11-18 02:50 UTC, kd8lvt commented
Thanks for your work :)
I've merged it here on GitHub, I'll release an update tomorrow or the day after to the Workshop. Feel free to poke me if I forget :)